config/routes.rb
Contacts::Application.routes.draw do
  devise_for :users#, :controllers => {:registrations => "registrations"}

  resources :contacts, except: [:show, :new, :edit] do
    get "by_tag/:tag", to: 'contacts#index', on: :collection, as: :tag
  end

  resources :cases, except: [:index]

  resources :tasks

  root :to => 'home#index'

end

app/models/contact.rb
# encoding: utf-8

class Contact < ActiveRecord::Base
  before_save :clean_data

  attr_accessible :last_name,
                  :name,
                  :tag_ids,
                  :company,
                  :info,
                  :position,
                  :entries_attributes,
                  :photo,
                  :remote_photo_url

  mount_uploader :photo, PhotoUploader

  has_many :contact_tag_associations, class_name: 'ContactTagAssociation'
  has_many :tags, through: :contact_tag_associations, dependent: :destroy
  has_many :business_contacts
  has_many :cases, through: :business_contacts, dependent: :destroy
  has_many :entries, class_name: 'ContactEntry', dependent: :destroy
  has_many :task_contact_associations
  has_many :tasks, through: :task_contact_associations, dependent: :destroy

  validates_presence_of :name
  # validates_associated :tags, :entries

  accepts_nested_attributes_for :entries, allow_destroy: true

  def clean_data
    self.name = self.name.tr(' ','')
    self.last_name = self.last_name.tr(' ','')
    self.position = self.position.strip()
    self.company = self.company.strip()
    self.info = self.info.strip()
  end

end



class EntryValidator < ActiveModel::Validator
  VALIDATION_RE = {
    email: /^[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,4})$/,
    phone: /^[+]?[\d]{1,3}?([\s]?\([\d]{3,6}\))?([\-\s]?[\d])*$/,
    fax: /^[+]?[\d]{1,3}?([\s]?\([\d]{3,6}\))?([\-\s]?[\d])*$/,
    skype: /^[\d\w\.\-]+$/,
    website: /^http(s)?:\/\/([\w\d\-]+\.)+[\w]{2,4}([\/][\w\d\-]+)*[\/]?$/,
    vk: /^http(s)?:\/\/([\w\d\-]+\.)*vk[\.]com[\/][\w\d\-]+$/,
    fb: /^http(s)?:\/\/(www.)?facebook[\.]com[\/][\w\d\-]+[\/]?$/,
    twttr: /^http(s)?:\/\/(www.)?twitter[\.]com[\/][\w\d\-]+[\/]?$/,
    gplus: /^http(s)?:\/\/(www.)?plus[\.]google[\.]com[\/](u\/0\/)?[\d]+([\/]|[\/]posts)?$/
  }

  def validate(record)
    unless record.entry =~ VALIDATION_RE[record.entry_type.to_sym]
      record.errors[:base] << "#{record.entry_type} entry is invalid"
    end
  end
end



class ContactEntry < ActiveRecord::Base
  TYPES = ['email', 'phone', 'fax', 'skype', 'website', 'vk', 'fb', 'twttr', 'gplus']
  #['E-mail','Телефон', 'Факс', 'Skype', 'Веб-сайт', 'Вконтакте', 'Facebook', 'Twitter', 'Google+']

  attr_accessible :entry_type, :entry, :comment
  validates_inclusion_of :entry_type, :in => TYPES
  validates_presence_of :entry_type, :entry
  validates :entry, :length => { :maximum => 150 }
  validates :comment, :length => { :maximum => 15 }
  validates_with EntryValidator
  belongs_to :contact

  scope :links, where(entry_type: ['website', 'vk', 'fb', 'twttr', 'gplus'])
  scope :not_links, where(entry_type: ['email', 'phone', 'fax', 'skype'])
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_filter :preload_cases

  def index
    @contact = Contact.new
    @contact.entries.build

    @contacts = Contact.scoped
    if params[:tag].present?
      @contact_ids = Contact.joins(:tags).where("tags.name = ?", params[:tag]).select('"contacts"."id"').map(&:id)
      @contacts = @contacts.where(id: @contact_ids)
      raise ActiveRecord::RecordNotFound if @contacts.empty?
    end

    tag_names = Tag.all.map { |tag| "'#{tag.name}'" }
    @tags = tag_names.join(',')
  end

  def create
    @contact = Contact.new(params[:contact])

    if params[:tags]
      tag_names = params[:tags].split(',')
      tag_ids = []
      tag_names.each { |tag_name| tag_ids.push Tag.find_or_create_by_name(tag_name).id }
      @contact.tag_ids = tag_ids
    end

    if @contact.save
      redirect_to action: 'index', notice: 'Contact was successfully created.'
    else
      @contacts = Contact.all

      tag_names = Tag.all.map { |tag| "'#{tag.name}'" }
      @tags = tag_names.join(',')

      render :index
    end
  end

  def update
    @contact = Contact.find(params[:id])
    @contacts = Contact.all

    if params[:tags]
      tag_names = params[:tags].split(',')
      tag_ids = []
      tag_names.each { |tag_name| tag_ids.push Tag.find_or_create_by_name(tag_name).id }
      @contact.tag_ids = tag_ids
    end

    if @contact.update_attributes(params[:contact])
      redirect_to action: 'index', notice: 'Contact was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to contacts_path }
      format.json { head :no_content }
    end
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
  def entry_icon_for(entry, options = {})
    image_tag "icons/#{entry.entry_type}.png", options
  end
end

app/views/contacts/_contact.html.slim
.row.contact
  .row-fluid.visible
    .span1.social
      = image_tag contact.photo.small, class: "photo"
      - unless contact.entries.links.empty?
        div
          - contact.entries.links.each do |entry| 
            = link_to entry.entry, class: "social-network", target: "_blank" do
              = entry_icon_for entry
    .span6.info
      h3 = "#{contact.name} #{contact.last_name}"
      div
        - if contact.company != '' and contact.position != ''
          = "#{contact.company}, #{contact.position}"
        - else
          = "#{contact.company}#{contact.position}"
      .tag-line
        - unless contact.tags.empty?
          i.icon-tags
          |  
          == contact.tags.map { |tag| link_to tag.name, tag_contacts_path(tag.name) }.join ', '
      - if contact.info != ''
        .info = contact.info

    .span4.contact-entries
      - contact.entries.not_links.each_with_index do |entry, i| 
        = content_tag :div, class: "entry-#{i}" do
          .ico = entry_icon_for entry
          .cnt-line 
            p = "#{entry.entry}"
            p.comment = "#{entry.comment}"

    .controls
      i.icon-chevron-down.vis
      i.icon-chevron-up.hid
      = link_to contact, method: :delete, data: { confirm: 'Are you sure?' } do
        i.icon-remove.hid.blue
      i.icon-edit.hid.blue
  = render 'form', contact: contact

app/views/contacts/_form.html.slim
= nested_form_for contact, html: { class: 'with_tags hidden' } do |f| 
  .row.form
    .span1.social
      = image_tag contact.photo? ? contact.photo.small : asset_path('small_default_photo.png')
      .upload-img
        i.icon-upload
        = f.file_field :photo, class: 'filefield'

    .span5.info
      .controls-row
        = f.text_field :name, placeholder: 'Имя'
        = f.text_field :last_name, placeholder: 'Фамилия'
      .controls-row
        = f.text_field :company, placeholder: 'Компания'
        = f.text_field :position, placeholder: 'Должность'
      .controls-row
        = f.text_area :info, placeholder: 'Дополнительная информация', rows: '5'
      .controls-row
        ul.tags
          - contact.tags.each do |tag| 
            li = tag.name

    .span3.contact-entries
      = f.fields_for :entries do |entry| 
        .controls-row
          .input-prepend
            span.add-on
              = entry.select :entry_type, ContactEntry::TYPES
            = entry.text_field :entry, placeholder: 'Контактная запись'
          = entry.link_to_remove do
            i.icon-remove
        .controls-row
          = entry.text_field :comment, class: 'comment', placeholder: 'Комментарий'
          span.help-block
            | Например:
            a.phone-type рабочий
            | ,
            a.phone-type домашний
            | ,
            a.phone-type мобильный
      .add-entry
        = f.link_to_add :entries, class: 'btn btn-small btn-block' do
          i.icon-plus
          |  Добавить запись
  .row
    .span8.offset1.actions
      = f.submit contact.id? ? 'Сохранить контакт' : 'Добавить контакт', class: 'btn btn-primary'
      button.btn.cancel type='button' Отмена

app/views/contacts/index.html.slim
= javascript_include_tag 'nested_form'
= javascript_include_tag 'tag-it'
= javascript_include_tag 'contacts'
= javascript_include_tag 'load-image.min'

.clearfix
  - if notice
    p.text-info
      = notice

  - if @contact.errors.any?
    ul
      - @contact.errors.full_messages.each do |msg| 
        li.text-error = msg

#add.row.contact
  .row.visible
    .span1.social 
      = image_tag asset_path('plus.png')
    .span4.info
      h3 Добавить контакт  
  = render 'form', contact: @contact
  
= render @contacts

erb:
  <script>
    $(document).ready(function() {
      var tags = [<%= @tags %>]
      $('.tags').tagit({
        placeholderText: 'Тэги',
        allowSpaces: true,
        availableTags: tags,
        singleField: true,
        removeConfirmation: true,
        showAutocompleteOnFocus: true
      });
      $('form.with_tags').submit(function() {
        $('input[type="submit"]').attr("disabled", "disabled");
      });
    });
  </script>