config/routes.rb
Contacts::Application.routes.draw do
  devise_for :users#, :controllers => {:registrations => "registrations"}

  resources :contacts, except: [:show, :new, :edit] do
    get "by_tag/:tag", to: 'contacts#index', on: :collection, as: :tag
  end

  resources :cases, except: [:index]

  resources :tasks

  root :to => 'home#index'

end

app/views/layouts/_footer.html.slim
footer

app/views/layouts/_header.html.slim
.navbar.navbar-fixed-top
	.navbar-inner
		.container
			a.btn.btn-navbar data-target=".nav-collapse" data-toggle="collapse"
				span.icon-bar
				span.icon-bar
				span.icon-bar
			a.brand href="/" Zадачник
			.container.nav-collapse
				ul.nav
					- if user_signed_in?
						= content_tag(:li, link_to('Контакты', contacts_path) , class: (:active if controller_name == 'contacts'))
				ul.nav.right
					- if user_signed_in?
						li = link_to "Send invite", :new_user_invitation
						li = link_to "Profile", :edit_user_registration
						li = link_to "Sign out", :destroy_user_session, :method => :delete
					- else
						li = link_to "Sign in", :new_user_session

app/views/layouts/_meta.html.slim
meta charset="utf-8"
meta name="viewport" content="width=device-width, initial-scale=1.0"
= csrf_meta_tags
= stylesheet_link_tag "application", :media => "all"
= favicon_link_tag '/favicon.ico'
link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/flick/jquery-ui.css"
	
= javascript_include_tag "application"
= yield(:scripts)

/ <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
/ <!--[if lt IE 9]>
/ <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
/ <![endif]-->


/ <!--<link href="images/favicon.ico" rel="shortcut icon">-->
/ <!--<link href="images/apple-touch-icon.png" rel="apple-touch-icon">-->
/ <!--<link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">-->
/ <!--<link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">-->

app/views/layouts/_sidebar.html.slim
ul.nav.nav-list
	- @cases.each do |c| 
		= link_to c, class:"to-case" do
			div
				= image_tag c.image.thumb
			= c.title
	= link_to "#add-case", :data => { :'toggle' => 'modal' }, class:"to-case plus" do
		div
			img src="/assets/plus.png"
		| Add case

    /
    / Всплывающее модальное окно
    /
    form
        .modal.hide.fade.loop-light#add-case tabindex="-1" role="dialog" aria-labelledby="newModalLabel" aria-hidden="true"
            .modal-header.our-header
                button.close type="button" data-dismiss="modal" aria-hidden="true" ×
                h3#newModalLabel Новый проект
            .modal-body.body-message

                .project-info
                    / Загрузка изображения
                    .upload-image
                        input type="text" value=""
                        .upload-logo
                            /TODO: Если не загружена картинка, выводить умолчание, если загружена- картинку
                            img src="/assets/case_icon.png"
                            / Как-то так: = image_tag @user.user_avatar_url if @user.user_avatar?
                        .canvasLoader#canvasLoader style=""
                            canvas
                        input.decorated-file type="file"

                    .main-info
                        / Title
                        .control-group.with-help
                            input type="text" placeholder="Введите название"
                            span.title-help.preview title="Дайте название вашему проекту" ?

                        / Description
                        .control-group.with-help
                            textarea#comments placeholder="Дайте описание"
                            span.title-help.preview title="Дайте описание проекта, его цели, предполагаемые сроки реализации" ?

                / Status
                .control-group
                    label.label-block Статус
                    .select-block
                        select
                            option В процессе
                            option Выиграно
                            option Проиграно

                / Contacts
                .control-group
                    label.label-block Связанные контакты
                    .contacts-block
                        /Должен быть на инпут, а список
                        input type="text" placeholder="Добавьте контакты"

            .modal-footer.popup-footer
                button.btn data-dismiss="modal" aria-hidden="true" Отмена
                input.btn.btn-primary type="submit" value="Создать проект"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<title><%= content_for?(:title) ? yield(:title) : "Zадачник" %></title>
	<%= render "layouts/meta" %>
</head>
<body>

<%= render "layouts/header" %>

<div class="container">
	<div class="content">
		<div class="row">
			<div class="span3">
				<% if user_signed_in? %>
					<%= render "layouts/sidebar" %>
				<% end -%>
			</div>
			<div class="span9">
				<%= yield %>
				
			</div>

		</div>
	</div>

	<%= render "layouts/footer" %>

</div>

</body>
</html>